parameters:
#    skimia_angular.example.class: Skimia\AngularBundle\Example

services:
    skimia_angular.bundle_manager:
        class: Skimia\AngularBundle\Components\BundleManager\BundleManager
        arguments: ["@kernel", "%skimia_angular.global_config%", "%skimia_angular.bundle_config%"]
    
    skimia_angular.twig.html_helpers:
        class: Skimia\AngularBundle\Components\TwigServices\HtmlHelpers
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
            
    skimia_angular.routing.router:
        class: Skimia\AngularBundle\Components\RoutingManager\RouterGenerator
        arguments: [@service_container]
        
    skimia_angular.javascript_generator:
        class: Skimia\AngularBundle\Components\JavascriptGenerator\AngularBaseGenerator
        arguments: [@service_container]
        
    skimia_angular.dependency_manager:
        class: Skimia\AngularBundle\Components\FileGenerator\DependencyManager
        arguments: [@kernel,@templating]

    skimia_angular.main_generator:
        class: Skimia\AngularBundle\Components\FileGenerator\MainGenerator
        arguments: [@service_container]
        
        
        
    skimia_angular.form.type.multiselect:
        class: Skimia\AngularBundle\Form\Type\MultiSelectType
        tags:
            - { name: form.type, alias: multiselect }
    

    skimia_angular.form.type.singleselect:
        class: Skimia\AngularBundle\Form\Type\SingleSelectType
        tags:
            - { name: form.type, alias: singleselect }
    

    skimia_angular.data.manager:
        class: Skimia\AngularBundle\Components\DataManager\DataManager
        arguments: [@service_container]

    skimia_angular.data.subscriber:
        class: Skimia\AngularBundle\Handler\DataHandler
        arguments: ["@skimia_angular.data.manager"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postDelete }

    angular_translator_generator:
        class: Skimia\AngularBundle\Components\Translation\AngularTranslatorGenerator
        arguments:  [@service_container]

    authentication_handler:
        class:  Skimia\AngularBundle\Handler\AuthenticationHandler
        arguments:  [@router]
        tags:
             - { name: kernel.event_listener, event: kernel.event_listener, method: handle }